// src/components/Groups/GroupCard/index.tsx
import Avatar from '#components/Avatar'
import Image from 'next/image'
import _ from './GroupCard.module.scss'

interface GroupCardProps {
  title: string
  isPublic: boolean
  image: string
  banner: string
  members: string[]
}

export default function GroupCard({
  banner,
  image,
  isPublic,
  title,
  members,
}: GroupCardProps) {
  return (
    <article className={_.container}>
      <div className={_.banner}>
        <Image
          src={banner}
          alt={title}
          width={300}
          height={100}
          layout='responsive'
          className={_.bannerImg}
          objectFit='cover'
          objectPosition='center'
        />
      </div>

      <div className={_.data}>
        <div className={_.avatar}>
          <Avatar src={image} size={55} className={_.avatarImg} />
        </div>
        <div className={_.info}>
          <h3 className={_.title}>{title}</h3>
          <div className={_.meta}>
            <span>{members.length} Miembros</span>
            <div className={_.type}>
              {isPublic ? '🌐 Público' : '🔒 Privado'}
            </div>
          </div>
        </div>
      </div>
    </article>
  )
}

// src/components/elements/groups/group-card.svelte
<script lang="ts">
	import Avatar from '#components/global/avatar.svelte'
	import type { Group } from '#types'
	export let group: Group
</script>

<article>
	<div class="banner">
		<img src={group.banner} alt={group.name} />
	</div>
	<div class="data">
		<div class="avatar">
			<Avatar src={group.image} border active />
		</div>
		<div class="details">
			<h3 class="name">{group.name}</h3>
			<div class="info">
				<p class="type">
					{group.type === 'private' ? '🔒 Privado' : '🌐 Publico'}
				</p>
				<p class="members">
					{group.members.length}
					{group.members.length > 1 ? 'Miembros' : 'Miembro'}
				</p>
			</div>
		</div>
	</div>
</article>

<style lang="scss">
	.banner {
		height: 130px;
		margin-bottom: 10px;
		img {
			width: 100%;
			height: 100%;
			object-fit: cover;
		}
	}
	article {
		cursor: pointer;
		padding: 10px;
		position: relative;
		&:hover {
			background-color: var(--background-card);
		}
	}
	.avatar {
		top: 0px;
		padding: 20px;
		left: 0;
		position: absolute;
	}
	.info {
		@include space-between;
	}
	.info .type,
	.info .members {
		font-size: 14px;
	}
	.name {
		font-weight: 600;
	}
</style>
